# Generated by Django 3.2 on 2021-04-16 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rent')),
                ('num_bed', models.SmallIntegerField(verbose_name='Number of Bedrooms')),
                ('num_bath', models.SmallIntegerField(verbose_name='Number of Bathrooms')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('p_type', models.CharField(choices=[('1', 'Apartment'), ('2', 'House'), ('3', 'Douplex'), ('4', 'Condo')], max_length=20, verbose_name='Property Type')),
                ('desc', models.TextField(max_length=500, verbose_name='Description')),
                ('photo', models.ImageField(upload_to='static/media/images', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/media/images/', verbose_name='Browse photo to upload')),
                ('propty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.property')),
            ],
        ),
    ]
