# Generated by Django 3.2 on 2021-04-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_application_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='url',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images', verbose_name='Browse photo to upload'),
        ),
    ]
