# Generated by Django 3.2 on 2021-04-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_property_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/applicationdetail', verbose_name='Browse photo to upload'),
        ),
        migrations.AlterField(
            model_name='applicationattachment',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/applicationdetail', verbose_name='Browse photo to upload'),
        ),
    ]
