# Generated by Django 3.2 on 2021-04-21 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0007_auto_20210421_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_date', models.DateField(auto_now=True, null=True)),
                ('social_Security_Number', models.CharField(max_length=10, verbose_name='Social Security Number')),
                ('date_of_Birth', models.DateField(verbose_name='Date of Birth')),
                ('email', models.CharField(max_length=50, verbose_name='Email Address')),
                ('move_in_Date', models.DateField(verbose_name='Move in Date')),
                ('occupant1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupant Name')),
                ('social_Security_Number1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Social Security Number')),
                ('date_of_Birth1', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email Address')),
                ('occupant2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupant Name')),
                ('social_Security_Number2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Social Security Number')),
                ('date_of_Birth2', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email Address')),
                ('cur_employer_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Employer')),
                ('cur_employer_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employer Address')),
                ('cur_employer_phone', models.CharField(max_length=10, verbose_name='Employer Phone')),
                ('cur_length_of_time', models.CharField(max_length=10, verbose_name='Length of Employment')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor')),
                ('income', models.IntegerField(verbose_name='Income')),
                ('income_Frequency', models.CharField(blank=True, max_length=12, null=True, verbose_name='Income Frequency')),
                ('former_Employer', models.CharField(blank=True, max_length=75, null=True, verbose_name='Former Employer')),
                ('former_Employer_Address', models.CharField(blank=True, max_length=350, null=True, verbose_name='Employer Address')),
                ('former_Employer_Phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Employer Phone')),
                ('pre_position', models.CharField(max_length=30, verbose_name='Former Position')),
                ('pre_length_of_time', models.CharField(max_length=10, verbose_name='Length of Employment')),
                ('pre_supervisor', models.CharField(max_length=30, verbose_name='Supervisor')),
                ('pre_approx_income', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Income')),
                ('former_Income_Frequency', models.CharField(blank=True, max_length=12, null=True, verbose_name='Income Frequency')),
                ('other_Income', models.IntegerField(blank=True, null=True, verbose_name='Other Income')),
                ('income_Source', models.CharField(blank=True, max_length=51, null=True, verbose_name='Income Source')),
                ('pets', models.BooleanField(verbose_name='Pets')),
                ('number_of_Pets', models.IntegerField(blank=True, null=True, verbose_name='Number of Pets')),
                ('kind_of_Pet', models.CharField(blank=True, max_length=25, null=True, verbose_name='Kind of Pets')),
                ('current_Address', models.CharField(max_length=100, verbose_name='Current Address')),
                ('current_City', models.CharField(max_length=30, verbose_name='City')),
                ('current_State', models.CharField(max_length=2, verbose_name='State')),
                ('current_Zip', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('current_Length_at_Address', models.CharField(max_length=25, verbose_name='Length at Address')),
                ('currently_Own', models.BooleanField(verbose_name='Own')),
                ('currently_Lease', models.BooleanField(verbose_name='Lease')),
                ('current_Lease_Expiration', models.DateField(blank=True, null=True, verbose_name='Lease Expiration')),
                ('current_Payee', models.CharField(max_length=40, verbose_name='Payee')),
                ('current_Payee_Phone', models.CharField(max_length=12, verbose_name='Payee Phone')),
                ('former_Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Former Address')),
                ('former_City', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('former_State', models.CharField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('former_Zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
                ('former_Length_at_Address', models.CharField(blank=True, max_length=25, null=True, verbose_name='Length at Address')),
                ('former_Own', models.BooleanField(verbose_name='Own')),
                ('former_Lease', models.BooleanField(verbose_name='Lease')),
                ('former_Lease_Expiration', models.DateField(blank=True, null=True, verbose_name='Lease Expiration')),
                ('former_Payee', models.CharField(blank=True, max_length=40, null=True, verbose_name='Payee')),
                ('former_Payee_Phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Payee Phone')),
                ('eviction', models.BooleanField(verbose_name='Eviction')),
                ('foreclosure', models.BooleanField(verbose_name='Foreclosure')),
                ('explanation', models.TextField(blank=True, max_length=250, null=True, verbose_name='Explanation')),
                ('emergency_Contact_Name', models.CharField(max_length=40, verbose_name='Emergency Contact')),
                ('relationship', models.CharField(max_length=20, verbose_name='Relationship')),
                ('emergency_Contact_Phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('emergency_Contact_Email', models.CharField(max_length=50, verbose_name='Email Address')),
                ('emergency_Contact_Address', models.CharField(max_length=100, verbose_name='Address')),
                ('emergency_Contact_City', models.CharField(max_length=50, verbose_name='City')),
                ('emergency_Contact_State', models.CharField(max_length=2, verbose_name='State')),
                ('emergency_Contact_Zip', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('file', models.ImageField(blank=True, null=True, upload_to='static/media/images/applicationdetail', verbose_name='Browse photo to upload')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.property')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='static/media/images/applicationdetail', verbose_name='Browse photo to upload')),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('propty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.property')),
            ],
        ),
    ]
